version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-coach-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/aicoach
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-coach-frontend
    volumes:
      - ./frontend:/app
      # Exclude node_modules from volume mounting to avoid conflicts
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    # Restart on failure to handle potential build issues
    restart: on-failure

  db:
    image: postgres:15
    container_name: ai-coach-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aicoach
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
